### ISSUE TITLE
Questions about semantic editing

### ISSUE THREAD

**Issue by fungtion** [RameenAbdal/StyleFlow#66]
Hi, in last paragraph of the section 6.2 in your paper, it said **"So, in our work the vectors of resultant W+ space are re-mapped to a new set of z0s using JRE followed by CFE and edit specific subset selection to perform a subsequent edit."**, is that means every time we perform editing, we should follow the order 6.2.1->6.2.2->6.2.3(perform Edit Specific Subset Selection in w+ space)? And I found in `real_time_editing` of `main.py`, the order became 6.2.1->6.2.3(perform Edit Specific Subset Selection in z0 space)->6.2.2, I don't know the reason. 

Besides, when editing "Beard", in your paper the indices are [5-7 and 10], but in your code, it is
 ```
self.rev[0][0][:5] = self.q_array[0][:5]
self.rev[0][0][10:] = self.q_array[0][10:]
``` 

and "Glasses", indices are [0-5] and [0-2], the code is:
```
self.rev[0][0][:2] = self.q_array[0][:2]
self.rev[0][0][4:] = self.q_array[0][4:]
```

Please help me.

**Comment by RameenAbdal** [comment]
For the first part, the confusion may be due to the naming. The order is the same as the paper. The order in which it is performed in 'real_time_editing' is cyclic 6.2.2->6.2.3->6.2.1 assuming we already have z0 ('self.fws' i.e 6.2.1 from the previous edit ). This repeats for the next sequential edit. For the second part, the final version of the paper is not out yet. We found these indices work better in terms of disentanglement.

**Comment by fungtion** [comment]
OK, thanks.
